### ISSUE TITLE
Christmas Meteor - 18th December 2014

### ISSUE THREAD

**Issue by alanshaw** [meteor-london/next#11]
- 18th December 2014
- **2nd Floor 50-52 Commercial Street E1 6LT, London**

Talks:
@alanshaw - Meat Fighter 2 Turbo
@juditgreskovits - Talk about portfolio site
@peterellisjones - Testing with TinyTest: everything is a package
@monbro - Speaking siri with agenda
@bmordan - Flickynotes
@richsilv - Publishing and modifying Meteor packages

**Comment by richsilv** [comment]
@richsilv - Publishing and modifying Meteor packages

**Comment by monbro** [comment]
I would be happy to do a lightning talk about doing a prototype for an art project about a speaking robot in a web interface which can listen to you as well. Like a siri with agenda.

**Comment by alanshaw** [comment]
@monbro sounds cool - I'll put your name down :)
@richsilv - legend as always

**Comment by alanshaw** [comment]
Hey @juditgreskovits @peterellisjones are you both still good to talk tomorrow night?

**Comment by peterellisjones** [comment]
Hi Alan,

Yeah I'm looking forward to it. I'll like to keep it short since I'm very
new to public speaking — is 10 minutes OK?

cheers,

Pete
ᐧ

_Peter Ellis Jones_
_Full Stack Developer_
London, UK
+44 0770 905 4244
Skype: petej205
pete@peterellisjones.com
www.peterellisjones.com
LinkedIn http://www.linkedin.com/profile/view?id=67971488&trk=tab_pro
Twitter http://twitter.com/peterellisjones Github
http://github.com/peterellisjones

**Comment by alanshaw** [comment]
That's fine dude, there'll be plenty of time for questions ;)

**Comment by monbro** [comment]
@alanshaw I just wanted to let you know that I need to leave at the latest point around 8:15 unfortunately - if it doesn't work out I am happy to do it next time as well :)

**Comment by bmordan** [comment]
This sounds awesome. Come prepared!
