### ISSUE TITLE
Meetup - September 2014

### ISSUE THREAD

**Issue by olizilla** [meteor-london/next#9]
When: **Thursday September 18th.**
What: 
- @evilpacket @daviddias - The Node Security Project
- @tomsteele -  Collaborative Penetration Testing (TBC)
- @liamwooding - Surround Cows Redux
- @bmordan - Testing with Velocity
- @charroch - TBC

Where: ustwo

Add a comment if you've got something you'd like to demo.

**Comment by olizilla** [comment]
@raedle are you available on the 18th to talk about huddle?

**Comment by charroch** [comment]
I have a project I could show off. It is a PR narrative. My first meteor/coffee/jade project. Took me couple of weeks on evenings to complete.

**Comment by olizilla** [comment]
@charroch If you're up for doing a lightening talk, we'd love to have you. Can you expand a little on _"it's a PR narrative"_?

**Comment by AndyWilkinUK** [comment]
@olizilla As per Meetup comment, doing a UX course part time at General Assembly, and going to do my project based on Meteor for Meteor. Can't tell you my idea (well just yet) as am not allowed to ask leading questions :)

At this stage I need to speak to 3-5 people of various skill levels with Meteor, for about 5 minutes to ask them about their experiences, challenges, etc.

So would appreciate it if you could give me a shout out to the gang at the end of the Meetup, I'll be coming tomorrow straight after I get out from class, and of course will buy some beers for all my fellow Meteor fans that want to be part of this crazy journey.

Will also be looking to send out a survey next month, and as get on with the project get feedback on prototypes and user testing. I'm hoping it will be crazy cool and that what I end up creating will be taken on by others in the community.

Probably will also reach out to the likes of Jade in SF, and other such as Differential and Percolate.

Oh and another thing, I did a Meteor live coding demo at work, which worked despite AV issues and think there may be a bug in the Mongo command line client - but that's another thing.

Cheers dude - and thanks for spending the time way back last year introducing me to this framework - it rocks....

**Comment by charroch** [comment]
A pull request narrative that lists all your Pull requests that are closed
in a narrative fashion. Couple of hours hacking meteor for the first time.
I ll confirm tomorrow that I am still coming as I might end up working late
unfortunately.

On 17 September 2014 09:45, Oli Evans notifications@github.com wrote:

> @charroch https://github.com/charroch If you're up for doing a
> lightening talk, we'd love to have you. Can you expand a little on _"it's
> a PR narrative"_?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/meteor-london/next/issues/9#issuecomment-55865344.

## 

Regards, Carl-Gustaf Harroch | CTO @ Novoda.com
Tel: +44 (0) 7 725 721 005

Disclaimer: The information in this e-mail and any attachments is the
property of Novoda Ltd and is confidential and may be legally privileged.
This e-mail is intended solely for the person or organisation to which it
is addressed. Any disclosure, copying or other use of the information by
any person or organisation who is not the intended recipient is strictly
prohibited and may be unlawful. If you have received this e-mail in error,
please inform the sender immediately and delete/destroy this e-mail and any
copies of it. Novoda Ltd has taken reasonable precautions to minimise the
risk of any software viruses which may damage your systems, but we advise
that you take the necessary steps to ensure that no virus contamination is
suffered. Novoda Ltd does not accept any liability for any loss or damage
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered Office:
C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT
Registration Number  GB 984 2525 93

## 

Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93

**Comment by olizilla** [comment]
@charroch sounds awesome! Please do come show it off!

@AndyWilkinUK sure thing! I'll announce it (feel free to remind me tomorrow ;-)  and am happy to help.
